server:
  port: 8000

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: user-server
          uri: lb://USER-SERVER
          predicates:
            - Path=/users/**
            - Path=/login
            - Path=/invitations
            - Path=/families
            - Path=/
            - Path=/pets
            - Path=/walking-records
            - Path=/feeding-records

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.instance.instance-id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG